whitelist:
  - Trisout78
  - Trisout
  - Notch
# HostnameWhitelist Config
hostname-enabled: true
warning: '&cYou entered the wrong IP address, please use &3example.com &cinstead'
ignore-case: true
block-legacy: true
allowed-host-names:
  - 'localhost'
custom-join-leave-message: true
# Whitelist command
whitelist-command-enabled: true
cooldown: 60 # cooldown in seconds